#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xtrans
Version  : 1.4.0
Release  : 15
URL      : http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.4.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.4.0.tar.gz
Source1  : http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.4.0.tar.gz.sig
Summary  : Abstract network code for X
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xtrans-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
xtrans - X Network Transport layer shared code
----------------------------------------------

%package dev
Summary: dev components for the xtrans package.
Group: Development
Provides: xtrans-devel = %{version}-%{release}
Requires: xtrans = %{version}-%{release}

%description dev
dev components for the xtrans package.


%package dev32
Summary: dev32 components for the xtrans package.
Group: Default
Requires: xtrans-dev = %{version}-%{release}

%description dev32
dev32 components for the xtrans package.


%package doc
Summary: doc components for the xtrans package.
Group: Documentation

%description doc
doc components for the xtrans package.


%package license
Summary: license components for the xtrans package.
Group: Default

%description license
license components for the xtrans package.


%prep
%setup -q -n xtrans-1.4.0
cd %{_builddir}/xtrans-1.4.0
pushd ..
cp -a xtrans-1.4.0 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604442213
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1604442213
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xtrans
cp %{_builddir}/xtrans-1.4.0/COPYING %{buildroot}/usr/share/package-licenses/xtrans/b7c6cc817dedc6e9c0aff3bb5a50cbc1e7f9548f
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xtrans/Xtrans.c
/usr/include/X11/Xtrans/Xtrans.h
/usr/include/X11/Xtrans/Xtransint.h
/usr/include/X11/Xtrans/Xtranslcl.c
/usr/include/X11/Xtrans/Xtranssock.c
/usr/include/X11/Xtrans/Xtransutil.c
/usr/include/X11/Xtrans/transport.c
/usr/lib64/pkgconfig/xtrans.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32xtrans.pc
/usr/lib32/pkgconfig/xtrans.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/xtrans/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xtrans/b7c6cc817dedc6e9c0aff3bb5a50cbc1e7f9548f
