#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xtrans
Version  : 1.3.5
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.3.5.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.3.5.tar.gz
Summary  : Abstract network code for X
Group    : Development/Tools
License  : MIT
Requires: xtrans-doc
BuildRequires : libxslt-bin
BuildRequires : xmlto

%description
xtrans is a library of code that is shared among various X packages to
handle network protocol transport in a modular fashion, allowing a
single place to add new transport types.  It is used by the X server,
libX11, libICE, the X font server, and related components.

%package dev
Summary: dev components for the xtrans package.
Group: Development

%description dev
dev components for the xtrans package.


%package doc
Summary: doc components for the xtrans package.
Group: Documentation

%description doc
doc components for the xtrans package.


%prep
%setup -q -n xtrans-1.3.5

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xtrans/Xtrans.c
/usr/include/X11/Xtrans/Xtrans.h
/usr/include/X11/Xtrans/Xtransint.h
/usr/include/X11/Xtrans/Xtranslcl.c
/usr/include/X11/Xtrans/Xtranssock.c
/usr/include/X11/Xtrans/Xtransutil.c
/usr/include/X11/Xtrans/transport.c
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/xtrans/*
